stages:
  - test

variables:
  PYTHONPATH: "."

before_script:
  - pip install -r requirements.txt

test_job:
  stage: test
  script:
    - pytest --alluredir=report
  artifacts:
    paths:
      - report
      - report.html
